FROM python:3.11-slim

WORKDIR /app

COPY requirements_docker.txt .
RUN pip install --no-cache-dir -r requirements_docker.txt

COPY structure.py main.py ./
COPY output/savedmodels ./output/savedmodels

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]